name: Update Projects Data

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  workflow_dispatch: # Allow manual triggers

jobs:
  update-projects:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Update projects data
        run: node .github/workflows/update-projects-script.cjs

      - name: Commit and push if changed
        run: |
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add -f public/projects-data.json public/scripts/slugify.js
          git commit -m "Update projects data" || echo "No changes to commit"
          git push || echo "No changes to push"
